import { type ChildProcess, spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ensureDatabase, type LocalPostgres, startLocalPostgres } from "@crm/db/local-postgres";
import { runMigrations } from "@crm/db/migrate";
import { isPortFree, pickFreePort } from "@crm/db/ports";

const root = fileURLToPath(new URL("..", import.meta.url));
const webDir = `${root}apps/web`;
const envFile = `${root}.env.local`;
const dataDir = `${root}.data/postgres`;
const DATABASE_NAME = "crm";
const DEFAULT_PORT = 3000;

function ensureEnvFile(): void {
  if (existsSync(envFile)) return;
  writeFileSync(
    envFile,
    [
      "# Generated by `pnpm dev` on first run. Git-ignored; see .env.example for all variables.",
      `APP_SECRET=${randomBytes(32).toString("hex")}`,
      "",
    ].join("\n"),
    { mode: 0o600 },
  );
  console.log("dev: created .env.local");
}

async function pickAppPort(): Promise<number> {
  if (process.env.PORT) {
    const port = Number(process.env.PORT);
    if (!Number.isInteger(port) || port <= 0) throw new Error(`invalid PORT: ${process.env.PORT}`);
    if (!(await isPortFree(port))) throw new Error(`PORT ${port} is already in use`);
    return port;
  }
  return (await isPortFree(DEFAULT_PORT)) ? DEFAULT_PORT : pickFreePort();
}

async function main(): Promise<number> {
  ensureEnvFile();
  process.loadEnvFile(envFile);

  let postgres: LocalPostgres | undefined;
  let next: ChildProcess | undefined;
  let stopping: Promise<void> | undefined;

  const stop = (): Promise<void> => {
    stopping ??= (async () => {
      if (next && next.exitCode === null && next.signalCode === null) {
        const child = next;
        const exited = new Promise((resolve) => child.once("exit", resolve));
        child.kill("SIGTERM");
        await Promise.race([exited, new Promise((resolve) => setTimeout(resolve, 5000))]);
        if (child.exitCode === null && child.signalCode === null) child.kill("SIGKILL");
      }
      await postgres?.stop();
    })();
    return stopping;
  };

  let finish: (code: number) => void = () => {};
  const exitCode = new Promise<number>((resolve) => {
    finish = resolve;
  });
  const shutdown = (code: number): void => {
    stop().then(
      () => finish(code),
      (error) => {
        console.error(error);
        finish(1);
      },
    );
  };
  for (const signal of ["SIGINT", "SIGTERM"] as const) {
    process.once(signal, () => {
      console.log(`\ndev: ${signal} received, shutting down`);
      shutdown(0);
    });
  }

  try {
    let databaseUrl = process.env.DATABASE_URL;
    if (!databaseUrl) {
      mkdirSync(dataDir, { recursive: true });
      postgres = await startLocalPostgres({ dataDir });
      await ensureDatabase(postgres.urlFor("postgres"), DATABASE_NAME);
      databaseUrl = postgres.urlFor(DATABASE_NAME);
      console.log(
        `dev: PostgreSQL ${postgres.adopted ? "already running" : "started"} on port ${postgres.port} (data in .data/postgres)`,
      );
    } else {
      console.log("dev: using DATABASE_URL from the environment");
    }

    const { applied, skipped } = await runMigrations(databaseUrl);
    console.log(`dev: migrations applied: ${applied.length}, already applied: ${skipped.length}`);

    const port = await pickAppPort();
    const appUrl = `http://127.0.0.1:${port}`;
    next = spawn("next", ["dev", "--hostname", "127.0.0.1", "--port", String(port)], {
      cwd: webDir,
      stdio: "inherit",
      env: {
        ...process.env,
        DATABASE_URL: databaseUrl,
        APP_URL: appUrl,
        PATH: `${webDir}/node_modules/.bin:${root}node_modules/.bin:${process.env.PATH}`,
      },
    });
    next.once("exit", (code) => {
      if (stopping) return;
      console.error(`dev: next exited unexpectedly (code ${code})`);
      shutdown(1);
    });

    console.log(`\n  App:      http://127.0.0.1:${port}`);
    console.log(`  Health:   http://127.0.0.1:${port}/api/health`);
    if (postgres) console.log(`  Database: ${databaseUrl}`);
    console.log("");
  } catch (error) {
    console.error(error);
    await stop();
    return 1;
  }

  return exitCode;
}

main().then((code) => process.exit(code));
